CREATE SCHEMA IF NOT EXISTS restapi_test;
SET SCHEMA restapi_test;

-- jwt_user
DROP TABLE IF EXISTS jwt_user;
CREATE TABLE IF NOT EXISTS jwt_user (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  client_id VARCHAR(100) NOT NULL DEFAULT '',
  client_secret VARCHAR(200) NOT NULL DEFAULT '',
  name VARCHAR(100) DEFAULT NULL,
  role VARCHAR(50) NOT NULL,
  primary key (id)
);
ALTER TABLE jwt_user ALTER COLUMN id RESTART WITH 3;

-- my_order
DROP TABLE IF EXISTS my_order;
CREATE TABLE IF NOT EXISTS my_order (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  user_id VARCHAR(255) NOT NULL,
  product_id INT NOT NULL,
  total_amount INT DEFAULT NULL,
  quantity INT NOT NULL,
  order_date TIMESTAMP NOT NULL,
  is_delete BOOLEAN NOT NULL DEFAULT FALSE,
  primary key (id)
);
ALTER TABLE my_order ALTER COLUMN id RESTART WITH 11;

-- create user for select  only
CREATE USER IF NOT EXISTS dbuser PASSWORD 'dbuser123';
GRANT SELECT ON jwt_user TO dbuser;
GRANT SELECT ON my_order TO dbuser;
REVOKE ALL ON SCHEMA PUBLIC FROM dbuser;